### ISSUE TITLE
Cannot install npm package @pangolin/cli

### ISSUE THREAD

**Issue by akmur** [pangolinjs/cli#4]
Hi, while trying to install the npm package with the command:

```
npm install -g @pangolin/cli
```

I get the error:

```
Cannot read property 'match' of undefined
```

Thanks!

**Comment by mvsde** [comment]
That was a rather strange issue with the included `npm-shrinkwrap.json` file. I have no idea what was wrong with the file, but removing it should fix this bug.

**Comment by akmur** [comment]
Hi, maybe I am missing something, but now the installation seems to run, howver in the end it says:

```
npm WARN deprecated circular-json@0.3.3: CircularJSON is in maintenance only, flatted is its successor.
npm ERR! Cannot read property 'match' of undefined
```
